name: bdp_payment_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  provider: ^6.1.1
  intl: ^0.19.0
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.7
  carousel_slider: ^4.2.1
  dio: ^5.4.1
  retry: ^3.1.2
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.7
  envied: ^0.5.3
  logger: ^2.0.2+1
  path_provider: ^2.0.11
  path: ^1.8.2
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.0.0
  shimmer: ^2.0.0
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.7
  pin_code_fields: ^8.0.1
  image_cropper: ^5.0.1
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2
  lottie: ^3.1.0

  # State Management
  get: ^4.6.5

  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  mask_text_input_formatter: ^2.9.0

  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  envied_generator: ^0.5.3
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.7


flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"

#  android_12 :
#    color: "#ffffff"
#    color_dark: "#272727"

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    ##- assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/images/successcreenimage/
    - assets/images/profile_image/
    - assets/images/banners/
    - assets/icons/
    - assets/animations/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf

    - family: IBMPlexSans-Bold
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf

    - family: IBMPlexSans-Medium
      fonts:
        - asset: assets/fonts/IBMPlexSans-Medium.ttf

    - family: IBMPlexSans-SemiBold
      fonts:
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
