name: bdp_payment_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.19.0
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.7
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  dio: ^5.1.1
  path_provider: ^2.0.11
  path: ^1.8.2
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  flutter_bloc: ^8.1.4
  provider: ^6.0.5
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.7
  pin_code_fields: ^8.0.1
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  flutter_image_compress: ^2.1.0

  # State Management
  get: ^4.6.5

  # Product Specific

  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    ##- assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/images/successcreenimage/
    - assets/images/profile_image/
    - assets/images/banners/
    - assets/icons/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
